spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: password
        url: jdbc:h2:file:./data/customerdb
        username: sa
        initialize: false
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    h2.console.enabled: true

logging:
    level:
        root: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
#To see the h2 db console. works only when application is running on server port 8080
#http://localhost:8080/h2-console
