spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 50
        password: lpras
        url: jdbc:mariadb://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8
        username: lpras
    application:
        name: my-jlc-bank-app
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
#Log Properties
logging:
    level:
        root: DEBUG
    pattern:
        console: '%-5level %logger{36} - %msg%n'


