spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: lpras
        url: jdbc:mariadb://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8
        username: lpras
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        root: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
