# RabbitMQ Properties
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
    level:
        root: INFO
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
server:
  port: 11111
